### ISSUE TITLE
[SP-H1] First depositor attack in Stability Pools

### ISSUE THREAD

**Issue by maarcweiss** [Shezmu-Team/shezmu-contracts#1]
## Description

The way on how the Stability pools has been designed is vulnerable to first depositor attacks:

```
 function deposit(uint256 amount) external nonReentrant {
     
        uint256 share = amountToShare(amount);

        shezUSD.safeTransferFrom(msg.sender, address(this), amount);

        _mint(msg.sender, share);
    }
```

- A hacker back-runs the transaction of an ERC4626 pool creation.
- The hacker mints for themself one share: deposit(1). Thus, totalAsset()==1, totalSupply()==1.
- The hacker front-runs the deposit of the victim who wants to deposit 20,000 USDT (20,000.000000).
- The hacker inflates the denominator right in front of the victim: asset.transfer(20_000e6). Now totalAsset()==20_000e6 + 1, totalSupply()==1.
- Next, the victim's tx takes place. The victim gets 1 * 20_000e6 / (20_000e6 + 1) == 0 shares. The victim gets zero shares.
- The hacker burns their share and gets all the money.

## Recommendation

Implement the uniswapv2 option of DEAD Shares. Though it does not fully mitigate the issue, I would advise the protocol to be the first depositor themselves, and deposit through flashbots (private mempool). Monitor also if another address has deposited previously.

**Comment by ShezmuTeam** [comment]
Thanks.
We will track total ShezUSD assets deposited/withdrawn to not count the assets transferred directly.
And will introduce a withdraw function for admin to withdraw any assets sent by accident.

**Comment by maarcweiss** [comment]
Fixed
