### ISSUE TITLE
[GLOBAL-M3] Stock Splits are unaccounted for.

### ISSUE THREAD

**Issue by maarcweiss** [Shezmu-Team/shezmu-contracts#11]
## Description
However, it's important to note that supporting equities comes with potential risks. One such risk is presented by forward stock splits, where a stock's price is halved, and the number of shares a user owns is doubled. Similar scenarios can also arise from reverse stock splits, mergers, and acquisitions.

For instance, in a 2-for-1 stock split, a shareholder receives an additional share for each share held. However, the token holder still holds only one ShezmuUSD token after the split. If a ShezmuUSD token holder owns 100 ShezmuUSD tokens before the split, he will still own 100 ShezmuUSD tokens after the split. However, he should own 200 ShezmuUSD tokens after the split.

Therefore, The ShezmuUSD token holder will gain or loss his ShezmuUSD token value after the stock split or reverse split.

## Recommendation

The Operator should have a mechanism to mint or burn ShezmuUSD tokens of holders when the underlying share is split or reverse split.

**Comment by ShezmuTeam** [comment]
could you elaborate more details please? shezUSD is collateral backed stablecoin.
