### ISSUE TITLE
[ERC721V-L1] Un-used whitelist role

### ISSUE THREAD

**Issue by maarcweiss** [Shezmu-Team/shezmu-contracts#16]
## Description
The whitelist role on the erc721vault contract is unused. 

```
 bytes32 public constant WHITELISTED_ROLE = keccak256('WHITELISTED_ROLE');
```

## Recommendation
Use the role in the create new auction function.

**Comment by ShezmuTeam** [comment]
fixed by https://github.com/Shezmu-Team/shezmu-contracts/pull/26

**Comment by maarcweiss** [comment]
Fixed
