### ISSUE TITLE
[GLOBAL-L6] Missing validation when updating the settings

### ISSUE THREAD

**Issue by maarcweiss** [Shezmu-Team/shezmu-contracts#22]
## Description
When updating the setting in the vaults, when initializing the erc20vault, there is validation so that all the rates in settings are within the valid ranges. 

Unfortunately, this validation is missing on the `setSettings` function.

## Recommendation

Add the same validation you already have in the constructor:

```diff
    function setSettings( 
        VaultSettings calldata _settings
    ) external onlyRole(SETTER_ROLE) {
+      if (
+            !_settings.debtInterestApr.isValid() ||
+            !_settings.debtInterestApr.isBelowOne()
+        ) revert RateLib.InvalidRate();

+        if (
+            !_settings.organizationFeeRate.isValid() ||
+            !_settings.organizationFeeRate.isBelowOne()
+        ) revert RateLib.InvalidRate();
     
        settings = _settings;
    }

```

**Comment by ShezmuTeam** [comment]
this is also partially fixed by https://github.com/Shezmu-Team/shezmu-contracts/pull/31

**Comment by maarcweiss** [comment]
Fixed
