### ISSUE TITLE
[GLOBAL-H4] totalDebtPortion is not updated when interest gets accrued

### ISSUE THREAD

**Issue by maarcweiss** [Shezmu-Team/shezmu-contracts#40]
## Description
When calling `accrue()`, the following three variables are updated:

```
        totalDebtAccruedAt = block.timestamp;
        totalDebtAmount += additionalInterest; 
        totalFeeCollected += additionalInterest;
```
Therefore it is updating the total debt, the fees and the time when teh debt was accrued. Despite that, there is a missing variable to be updated, which is `totalDebtPortion`.

## Recommendation

Calculate the new portion of debt counting the additional interest:

```diff
 uint256 additionalInterest = calculateAdditionalInterest();

        totalDebtAccruedAt = block.timestamp;

-        totalDebtAmount += additionalInterest;

        totalFeeCollected += additionalInterest;

+        uint256 _plusPortion = _calculatePortion(
+                totalDebtPortion,
+                additionalInterest,
+                totalDebtAmount
+            );

+        totalDebtPortion = totalDebtPortion + _plusPortion;

+        totalDebtAmount += additionalInterest;
   
        emit Accrual(additionalInterest);
```

**Comment by ShezmuTeam** [comment]
We don't update totalDebtPortion, users debt amount is calculated at totalDebtAmount * userDebtPortion / totalDebtPortion, so if we increase totalDebtPortion here, then it will not increase users debt amount accordingly

**Comment by maarcweiss** [comment]
ok, makes sense
