### ISSUE TITLE
[GLOBAL-H5] Interest is added to fees, inflating the stablecoin supply

### ISSUE THREAD

**Issue by maarcweiss** [Shezmu-Team/shezmu-contracts#44]
## Description

When accruing liabilities across the differents contracts from the codebase, the overall additional interest, is not just added to the total debt amount, it is also added to the total fee collected:

 `totalFeeCollected += additionalInterest; `

Then this can be collected by the DAO which will mint and dilute the stablecoin.

```
    function collect() external nonReentrant onlyRole(DAO_ROLE) {
        accrue();

        uint256 _totalFeeCollected = totalFeeCollected;

        stablecoin.mint(msg.sender, _totalFeeCollected);
        totalFeeCollected = 0;

        emit FeeCollected(_totalFeeCollected);
    }
```

## Recommendation

Remove the assignment of the additional interest to the fees`;

```diff
 function accrue() public {
        uint256 additionalInterest = calculateAdditionalInterest();

        totalDebtAccruedAt = block.timestamp;

        totalDebtAmount += additionalInterest;
        
-        totalFeeCollected += additionalInterest; 

        emit Accrual(additionalInterest);
    }
```

**Comment by ShezmuTeam** [comment]
Yeah, this is how we designed the fee mechanism.
if we don't increase totalFeeCollected here, then the DAO can't collect interest fees until users repay.
DAO will collect fees increasing users debt amount, this is how it works in JPEG'd as well.

**Comment by maarcweiss** [comment]
I do think it overinflates too much the supply, but if you are confident on the implementation, it should be nothing critical.
