### ISSUE TITLE
[GLOBAL-H3] Unsold NFTs will not be retrievable by creators

### ISSUE THREAD

**Issue by maarcweiss** [Shezmu-Team/shezmu-contracts#5]
## Description
Currently, in both auctions, if an NFT is unsold after the auction duration as ended, there is a function that supposely should allow the creator of the auction (the previous owner of the NFT) to recover their NFT:

```
  function withdrawUnsoldNFT(
        uint256 _auctionIndex
    ) external onlyRole(DEFAULT_ADMIN_ROLE) {
```

As the function has the `DEFAULT_ADMIN_ROLE` role and the check, the NFT will be able to be withdrawn only by the `DEFAULT_ADMIN_ROLE` and not the actual creator of the auction.

## Recommendation

Add a check so that the auction creator is the one that is able to withdraw their NFT to the `withdrawUnsoldNFT` functions accross the different ERC721-1155 Standards:

```diff
  function withdrawUnsoldNFT(
        uint256 _auctionIndex
-    ) external onlyRole(DEFAULT_ADMIN_ROLE) {
+    ) external {
     Auction storage auction = auctions[_auctionIndex];
+ if (auction.creator != msg.sender) revert Unauthorized();
```

**Comment by ShezmuTeam** [comment]
this is fixed by https://github.com/Shezmu-Team/shezmu-contracts/pull/26

**Comment by maarcweiss** [comment]
Fixed
