### ISSUE TITLE
[GLOBAL-H4] Users can abuse removing collateral to leave an insane amount of bad debt in the protocol.

### ISSUE THREAD

**Issue by maarcweiss** [Shezmu-Team/shezmu-contracts#6]
## Description
Currently, the `_removeCollateral` function allows users to remove collateral that they previously deposited in the contract. There is a missing check so that users are not able to "withdraw" enough collateral to leave their position liquidable. 

As you can see, there is currently a check so that the positions' debt, after withdrawing the collateral is not smaller than the credit limit of that account:

```
 uint256 _creditLimit = _getCreditLimit(
            _account,
            position.collateral - _colAmount
        );

        if (_debtAmount > _creditLimit) revert InsufficientCollateral();

        position.collateral -= _colAmount;
```

Though the check should be a different one, as you should be checking that the position is haelthy liquidation wise, instead of the credit limit

## Recommendation

Change the checks so that you can't remove more collateral to leave your position in a liquidatable state.

```diff
-       uint256 _creditLimit = _getCreditLimit(
-            _account,
-            position.collateral - _colAmount
-        );

-        if (_debtAmount > _creditLimit) revert InsufficientCollateral();
+       uint256 liquidationLimit = _getLiquidationLimit(
+            _account,
+            position.collateral - _colAmount
+        );
+        if (_debtAmount > liquidationLimit) revert InsufficientCollateral();

        position.collateral -= _colAmount;
```

**Comment by ShezmuTeam** [comment]
usually liquidation limit is 5 or 10% above the credit limit.
so credit limit check is more strict I think, @maarcweiss could you confirm if this is still a problem?

**Comment by maarcweiss** [comment]
If it is more strict, then you should be fine. I will update the issue accordingly. Thanks

**Comment by ShezmuTeam** [comment]
can we close this one then?
